# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68364faed3afa4c48cd7fe7dd893aaea5e596c694fafe21479edc1d817fa23a2829678306e815f266b3fe6582d5fd951a902e63e10931adee315b124a107e023

test:
  secret_key_base: f8b5059400cafe69355797a5c34490b00b7c7a761f58d98b39369a5663a1a6853c0b345064c7805d32e21f4a8cebf53913f51a63f3c8ffec320a746b028fcd9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
